### ISSUE TITLE
DS3622xs+ Support?

### ISSUE THREAD

**Issue by cclarke99** [pdbear/syno_nvidia_gpu_driver#1]
Does this package support the DS3622xs+? I'm following the instructions to use the physical GPU and when I try to run nvidia-smi, I get the following error.

/volume1/@appstore/NVIDIARuntimeLibrary/usr/bin# ./nvidia-smi
NVIDIA-SMI couldn't find libnvidia-ml.so library in your system. Please make sure that the NVIDIA Display Driver is properly installed and present in your system.
Please also try adding directory that contains libnvidia-ml.so to your system PATH.

Perhaps there are some path issues on this platform?

**Comment by pdbear** [comment]
您好，您的邮件已收到，我尽快回复您！

**Comment by cclarke99** [comment]
Seems that I missed a step and am making some progress now.

**Comment by pdbear** [comment]
DS_AAAA_XS+ series not supported now.

**Comment by ctaoist** [comment]
DS3622xs+ 7.1+ 版本的虚拟群晖求支持
