### ISSUE TITLE
DS1823xs+ support & nVidia T400 4GB support

### ISSUE THREAD

**Issue by hyllm** [pdbear/syno_nvidia_gpu_driver#10]
is this possible?

**Comment by hyllm** [comment]
<img width="654" alt="Snímka obrazovky 2024-01-05 o 10 24 26" src="https://github.com/pdbear/syno_nvidia_gpu_driver/assets/33330694/d877c82c-1440-4666-9fd1-25e24bb60e73">

So... P400 is working with no problems... :)

**Comment by hyllm** [comment]
<img width="737" alt="Snímka obrazovky 2024-01-05 o 10 26 15" src="https://github.com/pdbear/syno_nvidia_gpu_driver/assets/33330694/ee07b8d6-c7cb-40da-8d1b-694c7f508f7d">

**Comment by hyllm** [comment]
No problems at all with Plex. :)

<img width="641" alt="Snímka obrazovky 2024-01-05 o 10 41 36" src="https://github.com/pdbear/syno_nvidia_gpu_driver/assets/33330694/1a537cd9-e24d-47d0-b03d-dc5b99da944b">

**Comment by pdbear** [comment]
thanks alot
