### ISSUE TITLE
Concern about project maintenance and future GPU compatibility

### ISSUE THREAD

**Issue by Prevalent5948** [pdbear/syno_nvidia_gpu_driver#16]
Hello,

I want to start by saying a big thank you for your efforts on this project! The concept of utilizing NVIDIA GPUs with a Synology NAS is truly impressive and something I never thought possible.

However, I couldn't help but notice that there are no source files available in the repository or the linked sites from what I can see. This got me thinking about the long-term maintenance of the project. In case updates cease for an extended period, there's a risk that the GPU friver may not work with future NAS updates.

While I understand this might be unlikely, I believe including source files would be a valuable addition. Not only would it enhance transparency, but it would also instill greater confidence in users like myself who are considering implementing it in our own systems.

Thank you for working on this project! Your work is greatly appreciated.

**Comment by ianrahman** [comment]
@pdbear why not provide the source?
