### ISSUE TITLE
Please Help me check my setup GTX1050Ti

### ISSUE THREAD

**Issue by keitetran** [pdbear/syno_nvidia_gpu_driver#19]
My spec same above image. 
I have success install this driver. But on resource monitor GPU not working.
I play with plex and emby server. CPU is 100% only. GPU not work.
i can use this driver ? What i am missing ? 

Thank you verry much.

![image](https://github.com/pdbear/syno_nvidia_gpu_driver/assets/23551986/78a2fead-6fa6-4812-8531-a96400831245)
![image](https://github.com/pdbear/syno_nvidia_gpu_driver/assets/23551986/049434e9-9878-4e34-a66e-e219d867bf08)

**Comment by KennyH** [comment]
I am not associated with this project, but saw your issue when I was posting my feature request. 

Two guides that may help you troubleshoot or try different things:

1. [Guide: How to add a GPU to Synology DS1820+](https://www.reddit.com/r/synology/comments/16vl38e/guide_how_to_add_a_gpu_to_synology_ds1820/) -- covers setup and docker pass-through for Plex
2. [XPEnology Community - Nvidia Runtime Library](https://xpenology.com/forum/topic/22272-nvidia-runtime-library/) -- a long discussion on this topic that predates this project, but references it on the 5th page.

Also, if you would like help with your setup, more information about your issue would need to be provided. What is your system and GPU? How is Plex and Emby running on your system? Docker only or through spk? Stuff like that.

Wish you luck!

**Comment by keitetran** [comment]
Thank for comment. 
I tried it and success get GPU working now. 

My hardware: 
Motherboard: Quanmax MITX-DNV6
CPU Intel(R) Atom(TM) CPU C3538 @ 2.10GHz
RAM 16Gb
GPU NVIDIA GeForce GTX 1050 Ti
Bootloader: Arc (or RRorg)
DSM 7.2.1-69057 Update 5

Sortware:
Plex media server install from store
Plex Pass: Actived

Changelog: 
1. Install latest driver version https://github.com/pdbear/syno_nvidia_gpu_driver/releases
2. Execute command
```
# Command not found
nvidia-smi

# Fix 
vgpuDaemon fix
vgpuDaemon stop
vgpuDaemon start

# Try again (It worked)
nvidia-smi
```

3. Install patch from https://github.com/keylase/nvidia-patch

DONE !!! THANK YOU VERY MUCH 

![image](https://github.com/pdbear/syno_nvidia_gpu_driver/assets/23551986/d833b831-e824-4a27-a69b-4011a19cdbf6)
![image](https://github.com/pdbear/syno_nvidia_gpu_driver/assets/23551986/c50702da-156d-4cca-8863-668a6cf60a58)
