### ISSUE TITLE
System version DS3622xs+

### ISSUE THREAD

**Issue by sojab0on** [pdbear/syno_nvidia_gpu_driver#2]
Hi my xpenology nas is running on platform DS3622XS+ with DSM 7.1.1-42962 Update 6

I cant get the package installed due to the fact it requires DSM 7.2 and when i try to install that my bare-metal xpenology wont boot had to recreate my arl loader stick to get it up an running again 

do you have a version DSM 7.1.1-42962 Update 6

**Comment by pdbear** [comment]
not support any ds_aaaa_xs+ series.
