### ISSUE TITLE
Feature Request: Update for Cuda 12.1 or higher version

### ISSUE THREAD

**Issue by KennyH** [pdbear/syno_nvidia_gpu_driver#21]
First, I want to say that I appreciate this work immensely! You have done a wonderful job and I was very excited to try it out on my Synology DS1823xs+ with a T400 when I first learned about your work.

My request is to see if it were possible to update to have at least Cuda version 12.1 enabled. Currently, it is 12.0. 

I am requesting this because I would like to have a gpu-enabled instance of handbreak ([handbrake-nvenc-docker](https://github.com/zocker-160/handbrake-nvenc-docker)). And, unfortunately when I run it, it fails and says that it needs version 12.1 or higher and only 12.0 is detected.

Thank you for your consideration.

![image](https://github.com/pdbear/syno_nvidia_gpu_driver/assets/6706331/3abe20b9-018c-491c-b331-9221bca96b3c)

**Comment by pdbear** [comment]
ok, latest version update to cuda 12.2

**Comment by KennyH** [comment]
THANK YOU!

This is perfect now!
