### ISSUE TITLE
After using for a while, I got "Unable to determine the device handle for GPU0000:07:00.0: Unknown Error" in nvidia-smi

### ISSUE THREAD

**Issue by HappyZ** [pdbear/syno_nvidia_gpu_driver#22]
on DSM 7.2.1-69057 Update 5

on Synology DS1621+

Telsa P4 GPU

It was working fine and I rebooted it.

It now says unable to detect the GPU device. 

SSH'd into my NAS, `nvidia-smi` shows:

```
$ nvidia-smi
Unable to determine the device handle for GPU0000:07:00.0: Unknown Error
```

There weren't any errors and I can stop/start the NvidiaGPU Driver spk without any problems.

**Comment by pdbear** [comment]
tesla p4 need fan, it will over heat and shutdown if not.
