### ISSUE TITLE
DS1817+ DSM 7.2.1-69057

### ISSUE THREAD

**Issue by Postmortem71** [pdbear/syno_nvidia_gpu_driver#4]
Hello there,

Have tried to install your latest verion on DS1817+ DSM 7.2.1-69057. Unfortunately with no success. This package is not supported or is not compatible with the latest DSM version. May we please ask you to update the package.

Best regards
TheBjerke

**Comment by pdbear** [comment]
supported, please follow the tutorial，don't forget to execute `sudo vgouDaemon fix` and reboot twice.

**Comment by maah05** [comment]
Do still get the same error. Have tested with previous versions of your code as well.

**Comment by maah05** [comment]
Which tutorial do you refer to?
