### ISSUE TITLE
DS1621+ DSM 7.2-64570 Package Install Does not work

### ISSUE THREAD

**Issue by whizzzkid** [pdbear/syno_nvidia_gpu_driver#5]
Hey @pdbear

This work looks promising, however the package does not seem to install successfully.

Model: DS1621+
DSM: 7.2-64570

Symptoms:
- The package install seems to complete successfully.
- The executables and PATH never get updated.
- Results in `nvidia-smi command not found`

Investigation:
- Package is installed at `/volume1/@appstore/NVIDIARuntimeLibrary/`
- Running `/volume1/@appstore/NVIDIARuntimeLibrary/usr/bin/nvidia-smi` complains about `Please also try adding directory that contains libnvidia-ml.so to your system PATH.`
- `echo $PATH` results in `/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin` which does not have any of the `/volume1/@appstore/NVIDIARuntimeLibrary/usr/bin` files.

Can you please update the package to fix these paths?

**Comment by pdbear** [comment]
hey arora，you may forgot to execute `sudo vgpuDaemon fix` and reboot twice。



---Original---
From: "Nishant ***@***.***&gt;
Date: Tue, Oct 17, 2023 08:50 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [pdbear/syno_nvidia_gpu_driver] DS1621+ DSM 7.2-64570 PackageInstall Does not work (Issue #5)




 
On further probing, I tried installing the package using the CLI synopkg install:
 $ sudo -i # synopkg install NVIDIARuntimeLibrary-x86_64-510.108.03-common-gpuinfo-20230919.spk {    "error":{       "code":0    },    "results":[       {          "action":"upgrade",          "beta":false,          "betaIncoming":false,          "error":{             "code":0          },          "finished":true,          "installReboot":false,          "installing":true,          "language":"enu",          "last_stage":"started",          "package":"NVIDIARuntimeLibrary",          "packageName":"Nvidia GPU Driver",          "pid":16321,          "scripts":[             {                "code":0,                "message":"Nvidia vGPU Driver stopped\n",                "type":"stop"             },             {                "code":0,                "message":"",                "type":"preupgrade"             },             {                "code":0,                "message":"",                "type":"preuninst"             },             {                "code":0,                "message":"",                "type":"postuninst"             },             {                "code":0,                "message":"",                "type":"preinst"             },             {                "code":0,                "message":"",                "type":"postinst"             },             {                "code":0,                "message":"",                "type":"postupgrade"             },             {                "code":0,                "message":"Nvidia vGPU Driver started\n",                "type":"start"             }          ],          "spk":"NVIDIARuntimeLibrary-x86_64-510.108.03-common-gpuinfo-20230919.spk",          "stage":"installed_and_started",          "status":"running",          "status_code":0,          "status_description":"translate from systemd status",          "success":true,          "username":"",          "version":"1.2.3-0919"       }    ],    "success":true }
 
Which seems to indicate this worked. vgpuDaemon command exists and seems like it works 🤔

**Comment by pdbear** [comment]
supported, please follow the tutorial，don't forget to execute sudo `vgouDaemon fix` and reboot twice.
