### ISSUE TITLE
Old Gpu Support

### ISSUE THREAD

**Issue by Edwardpge** [pdbear/syno_nvidia_gpu_driver#6]
Hi, I want support for old gpus for xpenology i got an old GT30 is their any possiblity that might can work?

i would appreciate your concerned regarding this issue!

**Comment by pdbear** [comment]
this gpu is very old have no use value。

**Comment by Edwardpge** [comment]
> Hi, I want support for old gpus for xpenology i got an old GT30 is their any possiblity that might can work?
> 
> i would appreciate your concerned regarding this issue!

sorry for incorrect information i meant to say GT630 Nvidia
