### ISSUE TITLE
support RS1619xs+

### ISSUE THREAD

**Issue by lephino** [pdbear/syno_nvidia_gpu_driver#9]
Is there a reason this isn't currently supported on the 1619xs+?  When I install the card via a riser, I can get ta UID for the card and just need to get the drivers installed.  Is this something I can compile myself on the xs+?

Thanks for your work on this!

**Comment by pdbear** [comment]
fixed

**Comment by lephino** [comment]
Ty, gpu does show up and seems to work!  Thanks for all your time you've put in on this!
